language: node_js
node_js: 8.11.4
before_install: 
  apt install zip
  npm install
script: npm run build:prod && zip -r docs.zip docs docs
deploy:
  provider: pages
  local-dir: docs
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    all_branches: true